Streamlit UI for non technical users.
moest-np/center-randomize pull request #29
Opened 2024-04-21 13:45 UTC by aashu-kattel

2024-04-21 14:43 UTC, r-a-j-a-n commented
👏👏

2024-04-21 15:48 UTC, beingjungshahi commented on app.py
> +    main()
Add EOL.

2024-04-21 17:16 UTC, chinge55 requested changes
`streamlit` added without updating requirements.

2024-04-23 19:48 UTC, sumanashrestha commented
thank you for introducing streamlit 
merged #44 which was inspired from this PR

2024-04-23 19:48 UTC, closed without merging